### ISSUE TITLE
USER STORY: Manage a poll as a website administrator

### ISSUE THREAD

**Issue by TezzStrom** [TezzStrom/agile_development#4]
As a **website administrator** I can **update the poll** so that **the users get updated information about the poll**

#3 

### Acceptance Criteria:

- Acceptance criteria 1: Collect information from users and store in a database.
- Acceptance criteria 2: Publish new suggestions if applicable to the website for other users to vote for
- Acceptance criteria 3: Update the UI for the user to show the results from the poll

### Tasks

- [ ] Create a form for users to fill out with a submit button to send the form.
- [ ] Create a database to store the votes and information.
- [ ] Create a JavaScript file to handle the changing UI when the results are to be revealed to the user.
